const WP_PARAMS = global.WP_PARAMETERS

export const WP_URL = WP_PARAMS.API
export const SITE_URL = WP_PARAMS.SITE_URL
export const WP_HOST = WP_PARAMS.WP_HOST
export const WP_SITE_TITLE = WP_PARAMS.SITE_TITLE
export const WP_SITE_DESCRIPTION = WP_PARAMS.SITE_DESCRIPTION
export const WP_API = WP_PARAMS.API
export const WP_PAGE_FOR_POSTS = WP_PARAMS.PAGE_FOR_POSTS
export const WP_PAGE_ON_FRONT = WP_PARAMS.PAGE_ON_FRONT
export const WP_POSTS_PER_PAGE = WP_PARAMS.POSTS_PER_PAGE
export const GMAPS_API_KEY = WP_PARAMS.GMAPS_API_KEY
export const WP_NONCE = WP_PARAMS.NONCE
export const MAIN_MENU = WP_PARAMS.MAIN_MENU

export const REQUEST_API = 'REQUEST_API'
export const REQUEST_ARCHIVES = 'REQUEST_ARCHIVES'
export const REQUEST_PAGE_BY_SLUG = 'REQUEST_PAGE_BY_SLUG'
export const REQUEST_PAGE_BY_ID = 'REQUEST_PAGE_BY_ID'
export const REQUEST_ARCHIVE_BY_ID = 'REQUEST_ARCHIVE_BY_ID'
export const REQUEST_ARCHIVE_BY_SLUG = 'REQUEST_ARCHIVE_BY_SLUG'
export const REQUEST_MENU_BY_LOCATION = 'REQUEST_MENU_BY_LOCATION'
export const REQUEST_MENU_BY_ID = 'REQUEST_MENU_BY_ID'

export const RECEIVE_ARCHIVES = 'RECEIVE_ARCHIVES'
export const RECEIVE_ARCHIVE = 'RECEIVE_ARCHIVE'
export const RECEIVE_PAGE = 'RECEIVE_PAGE'
export const RECEIVE_MENU = 'RECEIVE_MENU'
export const RECEIVE_MENU_ITEMS = 'RECEIVE_MENU_ITEMS'
